global:
  message: Welcome to customer service prod environment!!
server:
  port: 8083
message: Hello from Prod!
spring:
  datasource:
     url: jdbc:postgresql://localhost:5432/cust_prod
     username: postgres
     password: 0000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
