global:
  message: Welcome to customer service dev environment!!
server:
  port: 8082
message: Hello from Dev!
spring:
  datasource:
     url: jdbc:postgresql://localhost:5432/customer_master
     username: postgres
     password: 0000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  
